[package]
name = "crabscale-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
crabscale-control = { path = "../crabscale-control" }
crabscale-proto = { path = "../crabscale-proto" }

[[bin]]
name = "crabscale"
path = "src/main.rs"
