[package]
name = "crabscale-harness"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
crabscale-control = { path = "../crabscale-control" }
crabscale-proto = { path = "../crabscale-proto" }
crabscale-server = { path = "../crabscale-server" }
crabscale-transport = { path = "../crabscale-transport" }
base64 = "0.22"
bytes = "1"
clap = { version = "4", features = ["derive"] }
h2 = "0.4"
http = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["io-util", "net", "rt", "rt-multi-thread", "macros", "sync", "time"] }
x25519-dalek = { version = "2", features = ["static_secrets", "getrandom"] }
